language: python
cache:
  pip: true
  directories:
    - node_modules
python:
  - 3.6
services:
  - docker
before_install:
  - if [ "$TRAVIS_PULL_REQUEST" = "true" ]; then git checkout $TRAVIS_PULL_REQUEST_BRANCH; fi
  - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash
  - source ~/.nvm/nvm.sh
  - nvm install 12
install:
  # use config from master branch
  # - wget -O requirements.txt https://raw.githubusercontent.com/OI-wiki/OI-wiki/master/requirements.txt
  # - wget -O package.json https://raw.githubusercontent.com/OI-wiki/OI-wiki/master/package.json
  # - wget -O package-lock.json https://raw.githubusercontent.com/OI-wiki/OI-wiki/master/package-lock.json
  - pip install -r requirements.txt
  - npm install -g clang-format # for clang-format
  - npm install .
script:
  - set -e
  - npx remark ./docs -o --silent
  - find . -type f -name "*.cpp" | xargs clang-format -i
  - git config --local user.email "15963390+24OI-bot@users.noreply.github.com"
  - git config --local user.name "24OI-bot"
  - git status
  - git diff --stat
  - echo $TRAVIS_PULL_REQUEST_SLUG
  - echo $TRAVIS_PULL_REQUEST_BRANCH
  - echo $TRAVIS_PULL_REQUEST
  - "if [ '$TRAVIS_PULL_REQUEST' = 'true' ]; then git remote add pr 'https://24OI-bot:${GH_TOKEN}@github.com/${TRAVIS_PULL_REQUEST_SLUG}.git'; fi"
  - "if [[ $(git diff --stat) != '' ]] && [ '$TRAVIS_PULL_REQUEST' = 'true' ]; then git add . && git commit -m 'style: format markdown files with remark-lint' && git push pr $TRAVIS_PULL_REQUEST_BRANCH -v; fi"
  - git log
  - set +e
